// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// S4_SCATTNLAY
NumericVector S4_SCATTNLAY(Rcpp::S4 fullstack);
RcppExport SEXP Rscattnlay_S4_SCATTNLAY(SEXP fullstackSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type fullstack(fullstackSEXP);
    __result = Rcpp::wrap(S4_SCATTNLAY(fullstack));
    return __result;
END_RCPP
}
