// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// S4_SCATTNLAY
NumericVector S4_SCATTNLAY(S4 fullstack);
RcppExport SEXP Rscattnlay_S4_SCATTNLAY(SEXP fullstackSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< S4 >::type fullstack(fullstackSEXP );
        NumericVector __result = S4_SCATTNLAY(fullstack);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// scattnlay_test
NumericVector scattnlay_test();
RcppExport SEXP Rscattnlay_scattnlay_test() {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        NumericVector __result = scattnlay_test();
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
