# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

S4_SCATTNLAY_PP <- function(fullstack) {
    .Call('_Rscattnlay_S4_SCATTNLAY_PP', PACKAGE = 'Rscattnlay', fullstack)
}

S4_AMPL <- function(fullstack) {
    .Call('_Rscattnlay_S4_AMPL', PACKAGE = 'Rscattnlay', fullstack)
}

S4_SCATTNLAY <- function(fullstack) {
    .Call('_Rscattnlay_S4_SCATTNLAY', PACKAGE = 'Rscattnlay', fullstack)
}

